/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROGRAM_H_RPCGEN
#define _PROGRAM_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define INTCONV ((rpc_uint)1)
#define INTCONV_1 ((rpc_uint)1)

#ifdef __cplusplus
#define toHex ((rpc_uint)1)
extern "C" int * tohex_1(int *, CLIENT *);
extern "C" int * tohex_1_svc(int *, struct svc_req *);
#define toOct ((rpc_uint)2)
extern "C" int * tooct_1(int *, CLIENT *);
extern "C" int * tooct_1_svc(int *, struct svc_req *);

#elif __STDC__
#define toHex ((rpc_uint)1)
extern  int * tohex_1(int *, CLIENT *);
extern  int * tohex_1_svc(int *, struct svc_req *);
#define toOct ((rpc_uint)2)
extern  int * tooct_1(int *, CLIENT *);
extern  int * tooct_1_svc(int *, struct svc_req *);

#else /* Old Style C */
#define toHex ((rpc_uint)1)
extern  int * tohex_1();
extern  int * tohex_1_svc();
#define toOct ((rpc_uint)2)
extern  int * tooct_1();
extern  int * tooct_1_svc();
#endif /* Old Style C */

#endif /* !_PROGRAM_H_RPCGEN */
