/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "program.h"

int *
tohex_1_svc(int *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */
	result=*argp;
	printf("%d->%x\n",result,result );
	return(&result);
}

int *
tooct_1_svc(int *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */
	result=*argp;
	printf("%d->%o\n",result,result );

	return(&result);
}
